node{
stage('SCM Checkout'){

git 'https://github.com/kakarlathanmayee/test'}
stag('Compil-Package'){
//Get maven homepath
def mvnHome : tool name: 'MAVEN_HOME', type: 'maven'
sh "${mvnHome}/bin/mvn package"}
}
